export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const FETCH_INFREDIENTS_FAILED = "FETCH_INFREDIENTS_FAILED";

export const ORDER_POST_SUCCESS = "ORDER_POST_SUCCESS";
export const ORDER_POST_FAILED = "ORDER_POST_FAILED";
export const LOADING = "LOADING";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED";
export const FETCH_ORDER_START = "FETCH_ORDER_Start";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
